# charts/auth-service/values.yaml
namespace: auth-service
image:
  repository: example.com/auth-service
  tag: latest
service:
  port: 5006
  type: LoadBalancer
  loadBalancerIP: "192.168.105.246" # IP 대역을 염두해서 설정할 것!
nginx:
  port: 80