apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.nginx.port | int }}
      targetPort: {{ .Values.nginx.port | int }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    app: {{ .Chart.Name }}-nginx



